### PR TITLE
Update to latest wabt.

### PR DESCRIPTION
**Pull request by nlewycky**

### CODE REVIEW

**Comment by axic** [comment]
Is this updating to a release of wabt?

**Comment by syrusakbary** [comment]
This PR updates wabt to the latest version, it has the changes needed to run SIMD test cases properly.
@pepyakin if we can do a release into crates.io as soon as the PR lands it would be great, we would like to do a release of wasmer soon and would prefer to use the original wabt-rs rather than a fork! :)

**Comment by pepyakin** [comment]
@syrusakbary wabt 0.9.0 is out!

**Comment by syrusakbary** [comment]
YAY! Thanks 🤗

**Pull request merged**
