### PR TITLE
Add support for WebAssembly optional features.

### PR DESCRIPTION
**Pull request by nlewycky**
Fixes "TODO: Actually set features."

Please let me know if you have suggestions on how to improve it.

### CODE REVIEW

**Comment by pepyakin** [comment]
Hello @nlewycky, thanks for your PR!

There are some things that could be improved here.

1. Can you make a pass of stable `rustfmt` here?
2. CI status checks report some failures, can you fix those?
3. I wonder if we can get away without breaking the public interface?

**Comment by nlewycky** [comment]
1. I used "rustfmt 1.2.0-stable (09940a70 2019-03-27)" but it caused a ton of unrelated changes.
2. Doh, should be fixed.
3. I was wondering the same thing. We could create a new function with more control for people who need it and leave the existing one with the default features?

Also, should we make the Features be set with a builder-style syntax, eg. Features::new().enable_simd().disable_reference_types()?

I also wish there was a way to create these functions based on features.def in wabt so that we don't have to update the features list as wabt changes. I can add code to the build.rs that prints text (say, .rs code) based on the features, but I don't know how to integrate that into lib.rs (no textual #include like in C++). I think I could do that with a builder syntax that uses strings, eg. Features::new().enable("simd"), but I dislike the lack of compile-time checking on available features.

I also don't really like the way both the wat2wasm caller and Module both have Features that they own, and which gets deep copied.

I'm also not entirely thrilled with the textual repetition for each feature.

**Comment by pepyakin** [comment]
> I was wondering the same thing. We could create a new function with more control for people who need it and leave the existing one with the default features?

Yes, exactly what I am thinking of.

> I also wish there was a way

Actually, there is. Take a look at https://github.com/pepyakin/binaryen-rs we are doing the similar thing in build.rs. There you can see an example of how to use `include!` as well.

That said, I think it shouldn't be necessary for now, since it is not a big burden to update the features every now and then.

**Comment by nlewycky** [comment]
> > I was wondering the same thing. We could create a new function with more control for people who need it and leave the existing one with the default features?
> 
> Yes, exactly what I am thinking of.

Done.

> > I also wish there was a way
> 
> Actually, there is. Take a look at https://github.com/pepyakin/binaryen-rs we are doing the similar thing in build.rs. There you can see an example of how to use `include!` as well.
> 
> That said, I think it shouldn't be necessary for now, since it is not a big burden to update the features every now and then.

OK! I'll leave it, then.

**Comment by pepyakin** [comment]
Thanks for the PR!

**Pull request merged**
